import { ThemeFamilyContent } from "./zed-theme";
import opacity from "hex-color-opacity";

const colors = {
  black: "#000",
  white: "#fff",
  green: "#c2ff0e",
  gray: "#8e8e8e",
  orange: "#ff5502",
  blue: "#4009ff",
  epic: "#ba3bff",
  rare: "#5da2f5",
  uncommon: "#72ed9a",
  common: "#c7c7c7",
  cyberAcme: "#01ff03",
  nuCaloric: "#fe0961",
  traxus: "#ff7701",
  sekiguchi: "#95f7c4",
  mida: {
    yellow: "#dae74e",
    blue: "#90e0e9",
  },
  arachne: "#ff0200",
  blueGray: "#344255",
  transparent: opacity("#000", 0),
};

const bg = (color: string) => {
  return opacity(color, 0.1);
};

const terminalColorsMap = {
  black: colors.black,
  cyan: colors.rare,
  blue: colors.blue,
  magenta: colors.epic,
  yellow: colors.green,
  white: colors.white,
  green: colors.cyberAcme,
  red: colors.arachne,
};

const terminalColors = {};

Object.keys(terminalColorsMap).forEach((key) => {
  const color = terminalColorsMap[key];
  terminalColors[`terminal.ansi.${key}`] = color;
  terminalColors[`terminal.ansi.bright_${key}`] = color;
  terminalColors[`terminal.ansi.dim_${key}`] = opacity(color, 0.8);
});

const ui = {
  success: colors.nuCaloric,
  successBg: bg(colors.nuCaloric),
  warning: colors.traxus,
  warningBg: bg(colors.traxus),
  error: colors.arachne,
  errorBg: bg(colors.arachne),
  new: colors.cyberAcme,
  updated: colors.rare,
  deleted: colors.orange,
  background: "#111111",
  bgLight: "#1F1F1F",
  foreground: opacity(colors.white, 0.8),
  primary: colors.green,
  secondary: colors.blue,
  accent: colors.white,
  border: opacity(colors.white, 0.4),
  muted: colors.gray,
};

const lightUi = {
  success: colors.nuCaloric,
  successBg: bg(colors.nuCaloric),
  warning: colors.traxus,
  warningBg: bg(colors.traxus),
  error: colors.arachne,
  errorBg: bg(colors.arachne),
  new: colors.black,
  updated: colors.blue,
  deleted: colors.orange,
  background: colors.white,
  bgLight: "#F0F0F0",
  foreground: opacity(colors.black, 0.8),
  primary: colors.green,
  secondary: colors.blue,
  accent: colors.black,
  border: opacity(colors.black, 0.3),
  muted: colors.gray,
};

export const theme: ThemeFamilyContent = {
  $schema: "https://zed.dev/schema/themes/v0.2.0.json",
  name: "Marathon Theme",
  author: "Zev Ross",
  themes: [
    {
      name: "Marathon Dark",
      appearance: "dark",
      style: {
        background: ui.background,
        border: opacity(ui.muted, 0.3),
        "border.disabled": opacity(ui.border, 0.5),
        "border.focused": ui.primary,
        "border.transparent": opacity(ui.border, 0.5),
        "border.variant": ui.border,
        "border.selected": ui.primary,
        conflict: ui.error,
        "conflict.background": ui.errorBg,
        "conflict.border": ui.error,
        created: ui.new,
        "created.background": bg(ui.new),
        "created.border": ui.new,
        deleted: ui.deleted,
        "deleted.background": bg(ui.deleted),
        "deleted.border": ui.deleted,
        "drop_target.background": opacity(ui.bgLight, 0.5),
        "editor.active_line_number": ui.primary,
        "editor.active_line.background": bg(ui.primary),
        "editor.background": ui.background,
        "editor.document_highlight.bracket_background": opacity(
          ui.secondary,
          0.8,
        ),
        "editor.document_highlight.read_background": opacity(ui.primary, 0.2),
        "editor.document_highlight.write_background": colors.blue,
        "editor.foreground": ui.foreground,
        "editor.gutter.background": ui.background,
        "editor.highlighted_line.background": bg(ui.primary),
        "editor.invisible": bg(ui.foreground),
        "editor.line_number": opacity(ui.foreground, 0.4),
        "editor.subheader.background": ui.bgLight,
        "editor.wrap_guide": bg(ui.foreground),
        "element.active": ui.primary,
        "element.background": bg(ui.primary),
        "element.disabled": bg(colors.blueGray),
        "element.hover": opacity(ui.primary, 0.3),
        "element.selected": opacity(ui.primary, 0.3),
        "elevated_surface.background": ui.bgLight,
        error: ui.error,
        "error.border": ui.error,
        "error.background": ui.errorBg,
        "ghost_element.active": ui.primary,
        "ghost_element.background": colors.transparent,
        "ghost_element.disabled": colors.blueGray,
        "ghost_element.hover": opacity(ui.muted, 0.2),
        "ghost_element.selected": opacity(ui.primary, 0.3),
        hidden: bg(colors.white),
        "hidden.border": bg(colors.white),
        hint: ui.primary,
        "hint.background": bg(ui.primary),
        "hint.border": ui.primary,
        icon: ui.primary,
        "icon.accent": ui.secondary,
        "icon.disabled": bg(ui.foreground),
        "icon.muted": bg(ui.primary),
        "icon.placeholder": bg(ui.primary),
        ignored: colors.common,
        "ignored.background": bg(colors.common),
        "ignored.border": colors.common,
        info: ui.primary,
        "info.background": ui.background,
        "info.border": ui.primary,
        "link_text.hover": ui.secondary,
        modified: ui.updated,
        "modified.background": bg(ui.updated),
        "modified.border": ui.updated,
        "pane.focused_border": ui.primary,
        "panel.background": ui.bgLight,
        "panel.focused_border": ui.primary,
        "panel.indent_guide": opacity(ui.primary, 0.4),
        "panel.indent_guide_active": ui.primary,
        "panel.indent_guide_hover": ui.primary,
        players: [
          {
            background: bg(ui.primary),
            cursor: ui.primary,
            selection: bg(ui.primary),
          },
          {
            background: bg(colors.cyberAcme),
            cursor: colors.cyberAcme,
            selection: bg(colors.cyberAcme),
          },
          {
            background: bg(colors.nuCaloric),
            cursor: colors.nuCaloric,
            selection: bg(colors.nuCaloric),
          },
          {
            background: bg(colors.traxus),
            cursor: colors.traxus,
            selection: bg(colors.traxus),
          },
          {
            background: bg(colors.sekiguchi),
            cursor: colors.sekiguchi,
            selection: bg(colors.sekiguchi),
          },
          {
            background: bg(colors.mida.yellow),
            cursor: colors.mida.blue,
            selection: bg(colors.mida.yellow),
          },
          {
            background: bg(colors.arachne),
            cursor: colors.arachne,
            selection: bg(colors.arachne),
          },
        ],
        predictive: ui.primary,
        "predictive.background": bg(ui.primary),
        "predictive.border": ui.primary,
        renamed: colors.uncommon,
        "renamed.background": bg(colors.uncommon),
        "renamed.border": colors.uncommon,
        "scrollbar.thumb.background": opacity(ui.primary, 0.8),
        "scrollbar.thumb.hover_background": ui.primary,
        "scrollbar.thumb.border": ui.secondary,
        "scrollbar.track.border": ui.secondary,
        "search.match_background": ui.secondary,
        "status_bar.background": ui.background,
        success: ui.success,
        "success.background": ui.successBg,
        "success.border": ui.success,
        "surface.background": ui.bgLight,
        "tab.active_background": ui.bgLight,
        "tab_bar.background": ui.background,
        "tab.inactive_background": ui.background,
        ...terminalColors,
        "terminal.background": ui.bgLight,
        "terminal.foreground": ui.foreground,
        "terminal.dim_foreground": opacity(ui.foreground, 0.5),
        "terminal.bright_foreground": ui.primary,
        text: ui.primary,
        "text.accent": ui.accent,
        "text.muted": ui.muted,
        "text.disabled": opacity(ui.muted, 0.6),
        "text.placeholder": opacity(ui.primary, 0.6),
        "title_bar.background": ui.background,
        "title_bar.inactive_background": colors.blueGray,
        "toolbar.background": ui.bgLight,
        unreachable: opacity(ui.foreground, 0.5),
        warning: ui.warning,
        "warning.background": ui.warningBg,
        "warning.border": ui.warning,
        syntax: {
          attribute: {
            color: colors.rare,
          },
          boolean: {
            color: colors.nuCaloric,
            font_weight: 700,
          },
          comment: {
            color: ui.muted,
            font_style: "italic",
          },
          "comment.doc": {
            color: ui.muted,
            font_style: "italic",
          },
          constant: {
            color: colors.epic,
            font_weight: 700,
          },
          constructor: {
            color: colors.green,
          },
          embedded: {
            color: colors.cyberAcme,
          },
          emphasis: {
            color: colors.green,
          },
          "emphasis.strong": {
            color: colors.green,
            font_weight: 700,
          },
          enum: {
            color: colors.rare,
          },
          function: {
            color: colors.rare,
            font_weight: 700,
          },
          hint: {
            color: colors.green,
          },
          keyword: {
            color: colors.green,
          },
          label: {
            color: colors.green,
          },
          link_text: {
            color: colors.blue,
          },
          link_uri: {
            color: colors.blue,
          },
          number: {
            color: colors.epic,
            font_weight: 700,
          },
          operator: {
            color: colors.green,
          },
          predictive: {
            color: opacity(colors.green, 0.5),
          },
          preproc: {
            color: colors.blueGray,
          },
          primary: {
            color: colors.blueGray,
          },
          property: {
            color: colors.uncommon,
            font_style: "italic",
          },
          punctuation: {
            color: colors.common,
          },
          "punctuation.list_marker": {
            color: colors.green,
          },
          "punctuation.markup": {
            color: colors.green,
          },
          selector: {
            color: colors.green,
          },
          tag: {
            color: colors.uncommon,
          },
          title: {
            color: colors.nuCaloric,
            font_weight: 700,
          },
          type: {
            color: colors.epic,
            font_weight: 700,
          },
          string: {
            color: colors.sekiguchi,
          },
          "text.literal": {
            color: colors.common,
          },
          variable: {
            color: colors.white,
          },
        },
      },
    },
    {
      name: "Marathon Light",
      appearance: "light",
      style: {
        background: lightUi.background,
        border: opacity(lightUi.border, 0.2),
        "border.disabled": opacity(lightUi.border, 0.5),
        "border.focused": lightUi.primary,
        "border.transparent": opacity(lightUi.border, 0.5),
        "border.variant": lightUi.border,
        "border.selected": lightUi.primary,
        conflict: lightUi.error,
        "conflict.background": lightUi.errorBg,
        "conflict.border": lightUi.error,
        created: lightUi.new,
        "created.background": bg(lightUi.new),
        "created.border": lightUi.new,
        deleted: lightUi.deleted,
        "deleted.background": bg(lightUi.deleted),
        "deleted.border": lightUi.deleted,
        "drop_target.background": opacity(ui.bgLight, 0.5),
        "editor.active_line_number": colors.black,
        "editor.active_line.background": opacity(lightUi.primary, 0.3),
        "editor.background": lightUi.background,
        "editor.document_highlight.bracket_background": lightUi.primary,
        "editor.document_highlight.read_background": opacity(
          lightUi.primary,
          0.2,
        ),
        "editor.document_highlight.write_background": colors.blue,
        "editor.foreground": lightUi.foreground,
        "editor.gutter.background": lightUi.background,
        "editor.highlighted_line.background": bg(lightUi.primary),
        "editor.invisible": bg(lightUi.foreground),
        "editor.line_number": opacity(lightUi.foreground, 0.4),
        "editor.subheader.background": lightUi.bgLight,
        "editor.wrap_glightUide": bg(lightUi.foreground),
        "element.active": lightUi.primary,
        "element.background": lightUi.primary,
        "element.disabled": bg(lightUi.bgLight),
        "element.hover": opacity(lightUi.primary, 0.3),
        "element.selected": lightUi.primary,
        "elevated_surface.background": lightUi.bgLight,
        error: lightUi.error,
        "error.border": lightUi.error,
        "error.background": lightUi.errorBg,
        "ghost_element.active": lightUi.primary,
        "ghost_element.background": colors.transparent,
        "ghost_element.disabled": colors.blueGray,
        "ghost_element.hover": opacity(lightUi.muted, 0.2),
        "ghost_element.selected": opacity(lightUi.primary, 0.3),
        hidden: bg(colors.white),
        "hidden.border": bg(colors.white),
        hint: lightUi.primary,
        "hint.background": bg(lightUi.primary),
        "hint.border": lightUi.primary,
        icon: lightUi.primary,
        "icon.accent": lightUi.secondary,
        "icon.disabled": bg(lightUi.foreground),
        "icon.muted": bg(lightUi.primary),
        "icon.placeholder": bg(lightUi.primary),
        ignored: colors.common,
        "ignored.background": bg(colors.common),
        "ignored.border": colors.common,
        info: lightUi.primary,
        "info.background": lightUi.background,
        "info.border": lightUi.primary,
        "link_text.hover": lightUi.secondary,
        modified: lightUi.updated,
        "modified.background": bg(lightUi.updated),
        "modified.border": lightUi.updated,
        "pane.focused_border": lightUi.primary,
        "panel.background": lightUi.bgLight,
        "panel.focused_border": lightUi.primary,
        "panel.indent_guide": lightUi.primary,
        "panel.indent_guide_active": lightUi.primary,
        "panel.indent_guide_hover": lightUi.primary,
        players: [
          {
            background: opacity(lightUi.primary, 0.7),
            cursor: lightUi.primary,
            selection: opacity(lightUi.primary, 0.7),
          },
          {
            background: bg(colors.cyberAcme),
            cursor: colors.cyberAcme,
            selection: bg(colors.cyberAcme),
          },
          {
            background: bg(colors.nuCaloric),
            cursor: colors.nuCaloric,
            selection: bg(colors.nuCaloric),
          },
          {
            background: bg(colors.traxus),
            cursor: colors.traxus,
            selection: bg(colors.traxus),
          },
          {
            background: bg(colors.sekiguchi),
            cursor: colors.sekiguchi,
            selection: bg(colors.sekiguchi),
          },
          {
            background: bg(colors.mida.yellow),
            cursor: colors.mida.blue,
            selection: bg(colors.mida.yellow),
          },
          {
            background: bg(colors.arachne),
            cursor: colors.arachne,
            selection: bg(colors.arachne),
          },
        ],
        predictive: lightUi.primary,
        "predictive.background": bg(lightUi.primary),
        "predictive.border": lightUi.primary,
        renamed: colors.uncommon,
        "renamed.background": bg(colors.uncommon),
        "renamed.border": colors.uncommon,
        "scrollbar.thumb.background": lightUi.primary,
        "scrollbar.thumb.hover_background": lightUi.primary,
        "scrollbar.thumb.border": lightUi.primary,
        "scrollbar.track.border": lightUi.secondary,
        "search.match_background": lightUi.primary,
        "status_bar.background": lightUi.background,
        success: lightUi.success,
        "success.background": lightUi.successBg,
        "success.border": lightUi.success,
        "surface.background": lightUi.bgLight,
        "tab.active_background": lightUi.bgLight,
        "tab_bar.background": lightUi.background,
        "tab.inactive_background": lightUi.background,
        ...terminalColors,
        "terminal.background": lightUi.bgLight,
        "terminal.foreground": lightUi.foreground,
        "terminal.dim_foreground": opacity(lightUi.foreground, 0.5),
        "terminal.bright_foreground": lightUi.primary,
        text: lightUi.foreground,
        "text.accent": lightUi.secondary,
        "text.muted": lightUi.muted,
        "text.disabled": opacity(lightUi.muted, 0.6),
        "text.placeholder": opacity(lightUi.muted, 0.6),
        "title_bar.background": lightUi.background,
        "title_bar.inactive_background": colors.blueGray,
        "toolbar.background": lightUi.bgLight,
        unreachable: opacity(lightUi.foreground, 0.5),
        warning: lightUi.warning,
        "warning.background": lightUi.warningBg,
        "warning.border": lightUi.warning,
        syntax: {
          attribute: {
            color: colors.blue,
          },
          boolean: {
            color: colors.nuCaloric,
            font_weight: 700,
          },
          comment: {
            color: lightUi.muted,
            font_style: "italic",
          },
          "comment.doc": {
            color: lightUi.muted,
            font_style: "italic",
          },
          constant: {
            color: colors.epic,
            font_weight: 700,
          },
          constructor: {
            color: colors.green,
          },
          embedded: {
            color: colors.cyberAcme,
          },
          emphasis: {
            color: colors.green,
          },
          "emphasis.strong": {
            color: colors.green,
            font_weight: 700,
          },
          enum: {
            color: colors.blue,
          },
          function: {
            color: colors.blue,
            font_weight: 700,
          },
          hint: {
            color: colors.green,
          },
          keyword: {
            color: "#A9E300",
            font_weight: 700,
          },
          label: {
            color: colors.green,
          },
          link_text: {
            color: colors.blue,
          },
          link_uri: {
            color: colors.blue,
          },
          number: {
            color: colors.epic,
            font_weight: 700,
          },
          operator: {
            color: opacity(colors.common, 0.5),
          },
          predictive: {
            color: opacity(colors.green, 0.5),
          },
          preproc: {
            color: ui.bgLight,
          },
          primary: {
            color: ui.bgLight,
          },
          property: {
            color: colors.blue,
            font_style: "italic",
          },
          punctuation: {
            color: opacity(colors.common, 0.5),
          },
          "punctuation.list_marker": {
            color: colors.epic,
          },
          "punctuation.markup": {
            color: colors.epic,
          },
          selector: {
            color: colors.green,
          },
          tag: {
            color: colors.uncommon,
          },
          title: {
            color: colors.nuCaloric,
            font_weight: 700,
          },
          type: {
            color: colors.epic,
            font_weight: 700,
          },
          string: {
            color: "#33E289",
          },
          "text.literal": {
            color: colors.common,
          },
          variable: {
            color: colors.black,
          },
        },
      },
    },
  ],
};
